In [1]:
### TODO Normalize using groupby('file'); Add seconds column; Add column saying who won

In [2]:
import pandas as pd
import numpy as np

In [3]:
copy_dmg = pd.read_csv('csgo-matchmaking-damage/esea_master_dmg_demos.part1.csv')

In [4]:
copy_grenades = pd.read_csv('csgo-matchmaking-damage/esea_master_grenades_demos.part1.csv')

In [5]:
copy_kills = pd.read_csv('csgo-matchmaking-damage/esea_master_kills_demos.part1.csv')

In [6]:
copy_meta = pd.read_csv('csgo-matchmaking-damage/esea_meta_demos.part1.csv')

In [7]:
master_grenades = copy_grenades
master_dmg = copy_dmg
master_kills = copy_kills
master_meta = copy_meta

In [8]:
master_dmg.head()

,file,round,tick,seconds,att_team,vic_team,att_side,vic_side,hp_dmg,arm_dmg,...,wp,wp_type,att_id,att_rank,vic_id,vic_rank,att_pos_x,att_pos_y,vic_pos_x,vic_pos_y
0,esea_match_13770997.dem,1,14372,111.8476,World,Animal Style,None,CounterTerrorist,1,0,...,Unknown,Unkown,0,0,76561198055054795,0,0.0000,0.00000,0.0000,0.000000
1,esea_match_13770997.dem,1,15972,124.3761,Animal Style,Hentai Hooligans,CounterTerrorist,Terrorist,18,9,...,USP,Pistol,76561198048742997,0,76561198082200410,0,-1499.6900,63.33829,-669.5558,-79.769570
2,esea_match_13770997.dem,1,16058,125.0495,Animal Style,Hentai Hooligans,CounterTerrorist,Terrorist,100,0,...,USP,Pistol,76561198055054795,0,76561197961009213,0,-1066.8740,3.44563,-614.1868,-91.707770
3,esea_match_13770997.dem,1,16066,125.1121,Hentai Hooligans,Animal Style,Terrorist,CounterTerrorist,12,7,...,Glock,Pistol,76561198082200410,0,76561198055054795,0,-747.3146,-49.32681,-1065.5560,9.381622
4,esea_match_13770997.dem,1,16108,125.4410,Animal Style,Hentai Hooligans,CounterTerrorist,Terrorist,15,7,...,USP,Pistol,76561198048742997,0,76561198082200410,0,-1501.8610,49.19798,-748.4188,-53.469220

In [9]:
master_dmg.dtypes

file                object
round                int64
tick                 int64
seconds            float64
att_team            object
vic_team            object
att_side            object
vic_side            object
hp_dmg               int64
arm_dmg              int64
is_bomb_planted       bool
bomb_site           object
hitbox              object
wp                  object
wp_type             object
att_id               int64
att_rank             int64
vic_id               int64
vic_rank             int64
att_pos_x          float64
att_pos_y          float64
vic_pos_x          float64
vic_pos_y          float64
dtype: object

In [10]:
master_dmg.isnull().head()

,file,round,tick,seconds,att_team,vic_team,att_side,vic_side,hp_dmg,arm_dmg,...,wp,wp_type,att_id,att_rank,vic_id,vic_rank,att_pos_x,att_pos_y,vic_pos_x,vic_pos_y
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [11]:
master_dmg.isnull().apply(sum)

file                     0
round                    0
tick                     0
seconds                515
att_team                 0
vic_team                 0
att_side                 0
vic_side                 0
hp_dmg                   0
arm_dmg                  0
is_bomb_planted          0
bomb_site          5129343
hitbox                   0
wp                       0
wp_type                  0
att_id                   0
att_rank                 0
vic_id                   0
vic_rank                 0
att_pos_x                0
att_pos_y                0
vic_pos_x                0
vic_pos_y                0
dtype: int64

In [12]:
master_dmg['bomb_site'] = master_dmg['bomb_site'].fillna(0)

In [13]:
bool_arr = [True for x in range(len(master_dmg))]

In [14]:
master_dmg = master_dmg.dropna()

In [15]:
master_dmg.isnull().apply(sum)

file               0
round              0
tick               0
seconds            0
att_team           0
vic_team           0
att_side           0
vic_side           0
hp_dmg             0
arm_dmg            0
is_bomb_planted    0
bomb_site          0
hitbox             0
wp                 0
wp_type            0
att_id             0
att_rank           0
vic_id             0
vic_rank           0
att_pos_x          0
att_pos_y          0
vic_pos_x          0
vic_pos_y          0
dtype: int64

In [16]:
master_dmg['att_side'].unique()#['att_team'].nunique()

array(['None', 'CounterTerrorist', 'Terrorist'], dtype=object)

In [17]:
master_dmg['vic_side'].unique()#['att_team'].nunique()

array(['CounterTerrorist', 'Terrorist'], dtype=object)

In [18]:
att = pd.get_dummies(master_dmg['att_side'])
att.head()

   CounterTerrorist  None  Terrorist
0                 0     1          0
1                 1     0          0
2                 1     0          0
3                 0     0          1
4                 1     0          0

In [19]:
vic = pd.get_dummies(master_dmg['vic_side'])
vic.head()

   CounterTerrorist  Terrorist
0                 1          0
1                 0          1
2                 0          1
3                 1          0
4                 0          1

In [20]:
X = vic.join(att, lsuffix='_vic', rsuffix='_att')

In [21]:
master_dmg['file'].unique()

array(['esea_match_13770997.dem', 'esea_match_13779704.dem',
       'esea_match_13779769.dem', ..., 'esea_match_13793001.dem',
       'esea_match_13793017.dem', 'esea_match_13793043.dem'], dtype=object)

In [22]:
master_dmg.columns

Index(['file', 'round', 'tick', 'seconds', 'att_team', 'vic_team', 'att_side',
       'vic_side', 'hp_dmg', 'arm_dmg', 'is_bomb_planted', 'bomb_site',
       'hitbox', 'wp', 'wp_type', 'att_id', 'att_rank', 'vic_id', 'vic_rank',
       'att_pos_x', 'att_pos_y', 'vic_pos_x', 'vic_pos_y'],
      dtype='object')

In [23]:
master_dmg.head(50)

,file,round,tick,seconds,att_team,vic_team,att_side,vic_side,hp_dmg,arm_dmg,...,wp,wp_type,att_id,att_rank,vic_id,vic_rank,att_pos_x,att_pos_y,vic_pos_x,vic_pos_y
0,esea_match_13770997.dem,1,14372,111.8476,World,Animal Style,None,CounterTerrorist,1,0,...,Unknown,Unkown,0,0,76561198055054795,0,0.0000,0.00000,0.0000,0.000000
1,esea_match_13770997.dem,1,15972,124.3761,Animal Style,Hentai Hooligans,CounterTerrorist,Terrorist,18,9,...,USP,Pistol,76561198048742997,0,76561198082200410,0,-1499.6900,63.33829,-669.5558,-79.769570
2,esea_match_13770997.dem,1,16058,125.0495,Animal Style,Hentai Hooligans,CounterTerrorist,Terrorist,100,0,...,USP,Pistol,76561198055054795,0,76561197961009213,0,-1066.8740,3.44563,-614.1868,-91.707770
3,esea_match_13770997.dem,1,16066,125.1121,Hentai Hooligans,Animal Style,Terrorist,CounterTerrorist,12,7,...,Glock,Pistol,76561198082200410,0,76561198055054795,0,-747.3146,-49.32681,-1065.5560,9.381622
4,esea_match_13770997.dem,1,16108,125.4410,Animal Style,Hentai Hooligans,CounterTerrorist,Terrorist,15,7,...,USP,Pistol,76561198048742997,0,76561198082200410,0,-1501.8610,49.19798,-748.4188,-53.469220
5,esea_match_13770997.dem,1,16188,126.0674,Hentai Hooligans,Animal Style,Terrorist,CounterTerrorist,94,0,...,Glock,Pistol,76561198082200410,0,76561198048742997,0,-756.2186,-80.94859,-1500.0780,60.658150
6,esea_match_13770997.dem,1,16210,126.2397,Hentai Hooligans,Animal Style,Terrorist,CounterTerrorist,6,0,...,Glock,Pistol,76561198082200410,0,76561198048742997,0,-751.6216,-55.69779,-1499.8930,61.623760
7,esea_match_13770997.dem,1,16496,128.4791,Animal Style,Hentai Hooligans,CounterTerrorist,Terrorist,13,6,...,USP,Pistol,76561198055191021,0,76561198133908390,0,-1878.2420,527.70950,-632.5327,69.109200
8,esea_match_13770997.dem,1,16510,128.5888,Hentai Hooligans,Animal Style,Terrorist,CounterTerrorist,87,0,...,Glock,Pistol,76561198037331400,0,76561198055054795,0,-1025.8290,-487.79010,-1051.8220,98.665190
9,esea_match_13770997.dem,1,16514,128.6201,Hentai Hooligans,Animal Style,Terrorist,CounterTerrorist,9,5,...,Glock,Pistol,76561198082200410,0,76561198055191021,0,-702.2363,93.98489,-1877.2500,530.408100
10,esea_match_13770997.dem,1,16530,128.7454,Animal Style,Hentai Hooligans,CounterTerrorist,Terrorist,13,6,...,USP,Pistol,76561198055191021,0,76561198082200410,0,-1875.6630,534.70570,-701.8441,95.101040
11,esea_match_13770997.dem,1,16530,128.7454,Animal Style,Hentai Hooligans,CounterTerrorist,Terrorist,3,1,...,USP,Pistol,76561198055191021,0,76561198133908390,0,-1875.6630,534.70570,-642.4961,60.087430
12,esea_match_13770997.dem,1,16562,128.9959,Animal Style,Hentai Hooligans,CounterTerrorist,Terrorist,13,6,...,USP,Pistol,76561198055191021,0,76561198082200410,0,-1880.1910,522.77540,-705.1382,86.387330
13,esea_match_13770997.dem,1,17014,132.5352,Hentai Hooligans,Animal Style,Terrorist,CounterTerrorist,9,5,...,Glock,Pistol,76561198082200410,0,76561198055191021,0,-789.0594,156.53080,-1878.8630,518.600800
14,esea_match_13770997.dem,1,17048,132.8015,Hentai Hooligans,Animal Style,Terrorist,CounterTerrorist,9,5,...,Glock,Pistol,76561198082200410,0,76561198055191021,0,-788.0546,159.64950,-1882.1120,507.525700
15,esea_match_13770997.dem,1,17104,133.2399,Animal Style,Hentai Hooligans,CounterTerrorist,Terrorist,41,0,...,USP,Pistol,76561198055191021,0,76561198082200410,0,-1882.5430,506.90220,-782.7830,176.015900
16,esea_match_13770997.dem,1,17252,134.3988,Hentai Hooligans,Animal Style,Terrorist,CounterTerrorist,92,0,...,Glock,Pistol,76561198798659644,0,76561198169360549,0,-1089.1350,-194.60180,-1890.5760,-358.882600
17,esea_match_13770997.dem,1,17338,135.0722,Hentai Hooligans,Animal Style,Terrorist,CounterTerrorist,8,0,...,Glock,Pistol,76561198798659644,0,76561198169360549,0,-1104.0010,-127.94100,-1888.1070,-367.580300
18,esea_match_13770997.dem,1,17426,135.7613,Hentai Hooligans,Animal Style,Terrorist,CounterTerrorist,7,3,...,Glock,Pistol,76561198798659644,0,76561198055191021,0,-1154.5410,-64.86525,-1849.7300,579.183200
19,esea_match_13770997.dem,1,17524,136.5287,Hentai Hooligans,Animal Style,Terrorist,CounterTerrorist,66,0,...,Glock,Pistol,76561198133908390,0,76561198055191021,0,-865.5694,184.44980,-1884.0980,514.415500
20,esea_match_13770997.dem,1,17814,138.7994,Animal Style,Hentai Hooligans,CounterTerrorist,Terrorist,100,0,...,USP,Pistol,76561198165334141,0,76561198798659644,0,-1948.8640,37.30251,-1254.8070,-222.829200
21,esea_match_13770997.dem,1,18446,143.7482,Hentai Hooligans,Animal Style,Terrorist,CounterTerrorist,12,7,...,Glock,Pistol,76561198133908390,0,76561198165334141,0,-1017.8600,158.37420,-1939.6870,-216.900200
22,esea_match_13770997.dem,1,18470,143.9361,Hentai Hooligans,Animal Style,Terrorist,CounterTerrorist,12,7,...,Glock,Pistol,76561198037331400,0,76561198165334141,0,-909.3470,-329.98460,-1944.6820,-217.387000
23,esea_match_13770997.dem,1,18580,144.7974,Hentai Hooligans,Animal Style,Terrorist,CounterTerrorist,10,5,...,Glock,Pistol,76561198037331400,0,76561198165334141,0,-905.7943,-285.38250,-1940.8970,-255.180500
24,esea_match_13770997.dem,1,18650,145.3456,Hentai Hooligans,Animal Style,Terrorist,CounterTerrorist,10,5,...,Glock,Pistol,76561198037331400,0,76561198165334141,0,-905.2878,-268.68420,-1941.7010,-273.611300
25,esea_match_13770997.dem,1,18662,145.4395,Animal Style,Hentai Hooligans,CounterTerrorist,Terrorist,100,0,...,USP,Pistol,76561198165334141,0,76561198037331400,0,-1941.7330,-273.89680,-905.2958,-269.668100
26,esea_match_13770997.dem,1,19726,153.7709,Hentai Hooligans,Animal Style,Terrorist,CounterTerrorist,11,6,...,Glock,Pistol,76561198133908390,0,76561198165334141,0,-1007.2900,-304.26620,-1552.4200,-2.620028
27,esea_match_13770997.dem,1,19794,154.3034,Hentai Hooligans,Animal Style,Terrorist,CounterTerrorist,14,8,...,Glock,Pistol,76561198133908390,0,76561198165334141,0,-1115.7620,-289.69380,-1560.3200,100.729600
28,esea_match_13770997.dem,1,19832,154.6009,Hentai Hooligans,Animal Style,Terrorist,CounterTerrorist,11,6,...,Glock,Pistol,76561198133908390,0,76561198165334141,0,-1159.9770,-260.06690,-1580.9760,114.460900
29,esea_match_13770997.dem,1,19850,154.7419,Hentai Hooligans,Animal Style,Terrorist,CounterTerrorist,11,6,...,Glock,Pistol,76561198133908390,0,76561198165334141,0,-1166.7850,-230.74190,-1577.0830,119.236900
30,esea_match_13770997.dem,1,19870,154.8985,Animal Style,Hentai Hooligans,CounterTerrorist,Terrorist,16,7,...,USP,Pistol,76561198165334141,0,76561198133908390,0,-1574.3100,122.29310,-1164.4300,-196.661100
31,esea_match_13770997.dem,1,20000,155.9164,Hentai Hooligans,Animal Style,Terrorist,CounterTerrorist,9,6,...,Glock,Pistol,76561198133908390,0,76561198165334141,0,-1202.2810,-257.38200,-1559.7360,158.171800
32,esea_match_13770997.dem,2,23922,186.5484,Hentai Hooligans,Animal Style,Terrorist,CounterTerrorist,70,0,...,HE,Grenade,76561198037331400,0,76561198169360549,0,-1973.1820,-2064.25500,-2741.2500,-1523.163000
33,esea_match_13770997.dem,2,24596,191.7478,Animal Style,Hentai Hooligans,CounterTerrorist,Terrorist,45,1,...,Deagle,Pistol,76561198169360549,0,76561198082200410,0,-2121.6410,-1264.05200,-2658.5190,-1487.576000
34,esea_match_13770997.dem,2,24786,193.2355,Animal Style,Hentai Hooligans,CounterTerrorist,Terrorist,44,1,...,Deagle,Pistol,76561198169360549,0,76561198037331400,0,-2117.3190,-1292.84200,-2785.2270,-1449.125000
35,esea_match_13770997.dem,2,24918,194.2691,Hentai Hooligans,Animal Style,Terrorist,CounterTerrorist,12,1,...,AK47,Rifle,76561198798659644,0,76561198048742997,0,-1558.5680,-980.86650,-1027.6200,-543.373400
36,esea_match_13770997.dem,2,26148,203.9003,Hentai Hooligans,Animal Style,Terrorist,CounterTerrorist,81,0,...,AK47,Rifle,76561198082200410,0,76561198165334141,0,-2046.3430,-1315.11400,-1986.1700,-1118.482000
37,esea_match_13770997.dem,2,26160,203.9943,Hentai Hooligans,Animal Style,Terrorist,CounterTerrorist,19,0,...,AK47,Rifle,76561198082200410,0,76561198165334141,0,-2046.3430,-1315.11400,-1989.8950,-1117.564000
38,esea_match_13770997.dem,2,26164,204.0256,Hentai Hooligans,Animal Style,Terrorist,CounterTerrorist,35,0,...,AK47,Rifle,76561198798659644,0,76561198055191021,0,-1553.5700,-860.62310,-1441.9430,-261.424200
39,esea_match_13770997.dem,2,26176,204.1196,Hentai Hooligans,Animal Style,Terrorist,CounterTerrorist,35,0,...,AK47,Rifle,76561198798659644,0,76561198055191021,0,-1554.7370,-860.38620,-1438.0760,-262.074400
40,esea_match_13770997.dem,2,26190,204.2292,Hentai Hooligans,Animal Style,Terrorist,CounterTerrorist,30,0,...,AK47,Rifle,76561198798659644,0,76561198055191021,0,-1554.7370,-860.38620,-1431.0550,-263.319300
41,esea_match_13770997.dem,2,26564,207.1577,Animal Style,Hentai Hooligans,CounterTerrorist,Terrorist,39,1,...,Deagle,Pistol,76561198169360549,0,76561198082200410,0,-1755.4880,-1869.99700,-1729.0770,-919.754900
42,esea_match_13770997.dem,2,26626,207.6432,Animal Style,Hentai Hooligans,CounterTerrorist,Terrorist,16,1,...,Deagle,Pistol,76561198169360549,0,76561198082200410,0,-1768.1790,-1869.55800,-1722.1790,-869.556600
43,esea_match_13770997.dem,2,26632,207.6902,Animal Style,Hentai Hooligans,CounterTerrorist,Terrorist,87,12,...,CZ,Pistol,76561198048742997,0,76561198798659644,0,-996.3995,-285.28900,-1022.5850,-572.507100
44,esea_match_13770997.dem,2,26634,207.7059,Hentai Hooligans,Animal Style,Terrorist,CounterTerrorist,88,16,...,AK47,Rifle,76561198798659644,0,76561198048742997,0,-1018.2110,-570.13180,-994.2050,-285.921900
45,esea_match_13770997.dem,2,28032,218.6526,Animal Style,Hentai Hooligans,CounterTerrorist,Terrorist,56,11,...,CZ,Pistol,76561198055054795,0,76561198037331400,0,-1100.7080,-971.17570,-1726.2020,-788.107700
46,esea_match_13770997.dem,2,28132,219.4356,Hentai Hooligans,Animal Style,Terrorist,CounterTerrorist,24,4,...,Negev,Heavy,76561197961009213,0,76561198055054795,0,-1506.9180,-745.70650,-1143.1020,-970.761500
47,esea_match_13770997.dem,2,28142,219.5139,Animal Style,Hentai Hooligans,CounterTerrorist,Terrorist,84,12,...,CZ,Pistol,76561198055054795,0,76561197961009213,0,-1146.5360,-971.11620,-1507.4020,-746.561500
48,esea_match_13770997.dem,2,28150,219.5766,Hentai Hooligans,Animal Style,Terrorist,CounterTerrorist,24,4,...,Negev,Heavy,76561197961009213,0,76561198055054795,0,-1507.6030,-746.90980,-1150.8850,-975.209200
49,esea_match_13770997.dem,2,28154,219.6079,Animal Style,Hentai Hooligans,CounterTerrorist,Terrorist,16,3,...,CZ,Pistol,76561198055054795,0,76561197961009213,0,-1152.0590,-976.20760,-1507.6920,-747.054300

In [24]:
round_num = pd.get_dummies(master_dmg['round'])

In [25]:
round_num.columns = ['round_' +str(i) for i in round_num.columns]
round_num.head()

,round_1,round_2,round_3,round_4,round_5,round_6,round_7,round_8,round_9,round_10,...,round_54,round_55,round_56,round_57,round_58,round_59,round_60,round_61,round_62,round_63
0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [26]:
X = X.join(round_num)

In [27]:
X = X.rename(columns = {'None':'None_att'})

In [28]:
X.head()

,CounterTerrorist_vic,Terrorist_vic,CounterTerrorist_att,None_att,Terrorist_att,round_1,round_2,round_3,round_4,round_5,...,round_54,round_55,round_56,round_57,round_58,round_59,round_60,round_61,round_62,round_63
0,1,0,0,1,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,1,1,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,1,1,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,1,0,0,0,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,1,1,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [29]:
def normalize(df, column):
    return (df[column] - df[column].mean()) / df[column].std()

In [30]:
master_std = master_dmg.groupby('file')['hp_dmg'].apply(np.std)
master_avg = master_dmg.groupby('file')['hp_dmg'].apply(np.mean)

In [31]:
### TODO Normalize using groupby('file'); Add seconds column

In [32]:
X = X.join(normalize(master_dmg, 'hp_dmg'))

In [33]:
master_dmg.columns

Index(['file', 'round', 'tick', 'seconds', 'att_team', 'vic_team', 'att_side',
       'vic_side', 'hp_dmg', 'arm_dmg', 'is_bomb_planted', 'bomb_site',
       'hitbox', 'wp', 'wp_type', 'att_id', 'att_rank', 'vic_id', 'vic_rank',
       'att_pos_x', 'att_pos_y', 'vic_pos_x', 'vic_pos_y'],
      dtype='object')

In [34]:
X = X.join(normalize(master_dmg, 'arm_dmg'))

In [35]:
X = X.rename(columns = {'hp_dmg':'hp_dmg_norm', 'arm_dmg': 'arm_dmg_norm'})

In [36]:
bomb_planted = pd.get_dummies(master_dmg['is_bomb_planted'])
bomb_planted.columns = ['bomb_planted_False', 'bomb_planted_True']

In [37]:
X = X.join(bomb_planted)

In [38]:
bomb_site = pd.get_dummies(master_dmg['bomb_site'])

In [39]:
bomb_site = bomb_site.rename(columns= {0:'Bomb_Not_Planted', 'A':'Planted_at_A', 'B':'Planted_at_B'})
bomb_site.head()

   Bomb_Not_Planted  Planted_at_A  Planted_at_B
0                 1             0             0
1                 1             0             0
2                 1             0             0
3                 1             0             0
4                 1             0             0

In [40]:
X = X.join(bomb_site)

In [41]:
X = X.join(pd.get_dummies(master_dmg['hitbox']).rename(columns={'8':'8_hitbox'}))

In [42]:
master_dmg.columns

Index(['file', 'round', 'tick', 'seconds', 'att_team', 'vic_team', 'att_side',
       'vic_side', 'hp_dmg', 'arm_dmg', 'is_bomb_planted', 'bomb_site',
       'hitbox', 'wp', 'wp_type', 'att_id', 'att_rank', 'vic_id', 'vic_rank',
       'att_pos_x', 'att_pos_y', 'vic_pos_x', 'vic_pos_y'],
      dtype='object')

In [43]:
master_dmg['wp'].unique()

array(['Unknown', 'USP', 'Glock', 'HE', 'Deagle', 'AK47', 'CZ', 'Negev',
       'P250', 'Mac10', 'Incendiary', 'Flash', 'M4A4', 'Bizon', 'AWP',
       'P90', 'UMP', 'Tec9', 'Molotov', 'FiveSeven', 'Famas', 'Swag7',
       'MP9', 'M4A1', 'Gallil', 'XM1014', 'Scout', 'Nova', 'MP7',
       'Scar20', 'SG556', 'AUG', 'P2000', 'Knife', 'DualBarettas',
       'SawedOff', 'Smoke', 'Zeus', 'G3SG1', 'M249', 'Bomb', 'Decoy'],
      dtype=object)

In [44]:
X = X.join(pd.get_dummies(master_dmg['wp']).rename(columns={'Unknown': 'Unknown_wp'}))

In [45]:
X = X.join(pd.get_dummies(master_dmg['wp_type']).rename(columns={'Unkown':'Unknown_type'}))

In [46]:
X.head()

,CounterTerrorist_vic,Terrorist_vic,CounterTerrorist_att,None_att,Terrorist_att,round_1,round_2,round_3,round_4,round_5,...,XM1014,Zeus,Equipment,Grenade,Heavy,Pistol,Rifle,SMG,Sniper,Unknown_type
0,1,0,0,1,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
1,0,1,1,0,0,1,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
2,0,1,1,0,0,1,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
3,1,0,0,0,1,1,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
4,0,1,1,0,0,1,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0

In [47]:
master_dmg.head()

,file,round,tick,seconds,att_team,vic_team,att_side,vic_side,hp_dmg,arm_dmg,...,wp,wp_type,att_id,att_rank,vic_id,vic_rank,att_pos_x,att_pos_y,vic_pos_x,vic_pos_y
0,esea_match_13770997.dem,1,14372,111.8476,World,Animal Style,None,CounterTerrorist,1,0,...,Unknown,Unkown,0,0,76561198055054795,0,0.0000,0.00000,0.0000,0.000000
1,esea_match_13770997.dem,1,15972,124.3761,Animal Style,Hentai Hooligans,CounterTerrorist,Terrorist,18,9,...,USP,Pistol,76561198048742997,0,76561198082200410,0,-1499.6900,63.33829,-669.5558,-79.769570
2,esea_match_13770997.dem,1,16058,125.0495,Animal Style,Hentai Hooligans,CounterTerrorist,Terrorist,100,0,...,USP,Pistol,76561198055054795,0,76561197961009213,0,-1066.8740,3.44563,-614.1868,-91.707770
3,esea_match_13770997.dem,1,16066,125.1121,Hentai Hooligans,Animal Style,Terrorist,CounterTerrorist,12,7,...,Glock,Pistol,76561198082200410,0,76561198055054795,0,-747.3146,-49.32681,-1065.5560,9.381622
4,esea_match_13770997.dem,1,16108,125.4410,Animal Style,Hentai Hooligans,CounterTerrorist,Terrorist,15,7,...,USP,Pistol,76561198048742997,0,76561198082200410,0,-1501.8610,49.19798,-748.4188,-53.469220

Now we will join master_meta to master_dmg based on 'file' and 'round'

In [48]:
master_meta.head()

,file,map,round,start_seconds,end_seconds,winner_team,winner_side,round_type,ct_eq_val,t_eq_val
0,esea_match_13770997.dem,de_overpass,1,94.30782,160.9591,Hentai Hooligans,Terrorist,PISTOL_ROUND,4300,4250
1,esea_match_13770997.dem,de_overpass,2,160.95910,279.3998,Hentai Hooligans,Terrorist,ECO,6300,19400
2,esea_match_13770997.dem,de_overpass,3,279.39980,341.0084,Hentai Hooligans,Terrorist,SEMI_ECO,7650,19250
3,esea_match_13770997.dem,de_overpass,4,341.00840,435.4259,Hentai Hooligans,Terrorist,NORMAL,24900,23400
4,esea_match_13770997.dem,de_overpass,5,435.42590,484.2398,Animal Style,CounterTerrorist,ECO,5400,20550

In [49]:
master_dmg.head()

,file,round,tick,seconds,att_team,vic_team,att_side,vic_side,hp_dmg,arm_dmg,...,wp,wp_type,att_id,att_rank,vic_id,vic_rank,att_pos_x,att_pos_y,vic_pos_x,vic_pos_y
0,esea_match_13770997.dem,1,14372,111.8476,World,Animal Style,None,CounterTerrorist,1,0,...,Unknown,Unkown,0,0,76561198055054795,0,0.0000,0.00000,0.0000,0.000000
1,esea_match_13770997.dem,1,15972,124.3761,Animal Style,Hentai Hooligans,CounterTerrorist,Terrorist,18,9,...,USP,Pistol,76561198048742997,0,76561198082200410,0,-1499.6900,63.33829,-669.5558,-79.769570
2,esea_match_13770997.dem,1,16058,125.0495,Animal Style,Hentai Hooligans,CounterTerrorist,Terrorist,100,0,...,USP,Pistol,76561198055054795,0,76561197961009213,0,-1066.8740,3.44563,-614.1868,-91.707770
3,esea_match_13770997.dem,1,16066,125.1121,Hentai Hooligans,Animal Style,Terrorist,CounterTerrorist,12,7,...,Glock,Pistol,76561198082200410,0,76561198055054795,0,-747.3146,-49.32681,-1065.5560,9.381622
4,esea_match_13770997.dem,1,16108,125.4410,Animal Style,Hentai Hooligans,CounterTerrorist,Terrorist,15,7,...,USP,Pistol,76561198048742997,0,76561198082200410,0,-1501.8610,49.19798,-748.4188,-53.469220

In [50]:
master_join = master_dmg.merge(master_meta, on=['file', 'round'], how='outer')

In [51]:
len(master_join)

5991602

In [52]:
len(master_join[master_join['start_seconds'].isnull()]) / len(master_join)

0.00796431405156751

In [53]:
master_join = master_join[master_join['tick'].isnull()==False]

In [54]:
len(master_join)

5991582

In [55]:
len(X)

5991582

In [56]:
len(master_join)

5991582

In [57]:
master_join = master_join.reset_index(drop=True)
X = X.reset_index(drop=True)

In [58]:
X = X[master_join['winner_team'].isnull() == False]

In [59]:
len(X)

5943827

In [60]:
X.head()

,CounterTerrorist_vic,Terrorist_vic,CounterTerrorist_att,None_att,Terrorist_att,round_1,round_2,round_3,round_4,round_5,...,XM1014,Zeus,Equipment,Grenade,Heavy,Pistol,Rifle,SMG,Sniper,Unknown_type
0,1,0,0,1,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
1,0,1,1,0,0,1,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
2,0,1,1,0,0,1,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
3,1,0,0,0,1,1,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
4,0,1,1,0,0,1,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0

In [61]:
X.columns

Index(['CounterTerrorist_vic', 'Terrorist_vic', 'CounterTerrorist_att',
       'None_att', 'Terrorist_att', 'round_1', 'round_2', 'round_3', 'round_4',
       'round_5',
       ...
       'XM1014', 'Zeus', 'Equipment', 'Grenade', 'Heavy', 'Pistol', 'Rifle',
       'SMG', 'Sniper', 'Unknown_type'],
      dtype='object', length=134)

In [62]:
X.head()

,CounterTerrorist_vic,Terrorist_vic,CounterTerrorist_att,None_att,Terrorist_att,round_1,round_2,round_3,round_4,round_5,...,XM1014,Zeus,Equipment,Grenade,Heavy,Pistol,Rifle,SMG,Sniper,Unknown_type
0,1,0,0,1,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
1,0,1,1,0,0,1,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
2,0,1,1,0,0,1,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
3,1,0,0,0,1,1,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
4,0,1,1,0,0,1,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0

In [63]:
len(X) == len(master_join)

False

In [64]:
master_join = master_join.dropna()

In [65]:
len(X) == len(master_join)

True

In [66]:
y = pd.get_dummies(master_join['winner_side'])

In [67]:
len(X) == len(y)

True

In [68]:
X['hp_dmg_norm'] = master_join.groupby('file')['hp_dmg'].transform(lambda x: (x - x.mean()) / x.std())

In [69]:
X['arm_dmg_norm'] = master_join.groupby('file')['arm_dmg'].transform(lambda x: (x - x.mean()) / x.std())

In [70]:
X['seconds_norm'] = master_join.groupby('file')['seconds'].transform(lambda x: (x - x.mean()) / x.std())

In [71]:
maps = pd.get_dummies(master_join['map'])
X = X.join(maps)

In [72]:
round_types = pd.get_dummies(master_join['round_type'])
X = X.join(round_types)

In [73]:
X['ct_eq_val_norm'] = master_join.groupby('file')['ct_eq_val'].transform(lambda x: (x - x.mean()) / x.std())

In [74]:
X['t_eq_val_norm'] = master_join.groupby('file')['t_eq_val'].transform(lambda x: (x - x.mean()) / x.std())

In [75]:
#X.to_csv('csgo_data_cleaning/esea_master_dmg_meta_cleaned.pt1.csv', index = False)

In [77]:
#y.to_csv('csgo_data_cleaning/esea_master_dmg_meta_cleaned_pred.pt1.csv', index = False)